version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    # In order to make nginx have and don't conflict,
    # We change server service to api
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment: 
            # "Key=value" will be set hear. "Key" will take value from comp env. 
            # redis is service that was create above and it is a host
            - REDIS_HOST=redis
            # Pors is 6379 by deafult in doc 
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - postgres
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        environment: 
            - CI=true
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '8080:80'
        depends_on: 
            - api
            - client